# Generated by Django 4.1.1 on 2022-09-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='accs_tec',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='cel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='con_int',
            field=models.BooleanField(blank=True, choices=[('Si', 'Si'), ('No', 'No')]),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='cuales',
            field=models.CharField(choices=[('T movil', 'Telefono movil'), ('Computador', 'Computador'), ('Tablet', 'Tablet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='dire',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'femenino'), ('INTERSEXUAL', 'Intersexual'), ('INDEFINIDO', 'Indefinido'), ('NA', 'NA')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='tel',
            field=models.IntegerField(blank=True),
        ),
    ]
