# Generated by Django 4.1.1 on 2022-09-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='con_int',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True),
        ),
    ]
