# Generated by Django 4.1.1 on 2022-09-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='accs_tec',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='con_int',
            field=models.BooleanField(default=True),
        ),
    ]
