# Generated by Django 4.1.1 on 2022-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0002_alter_ciudadano_accs_tec_alter_ciudadano_cel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudadano',
            name='accs_tec',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='con_int',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='cuales',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='estrato',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='etnia',
        ),
        migrations.RemoveField(
            model_name='ciudadano',
            name='reg',
        ),
        migrations.RemoveField(
            model_name='sondeo',
            name='hora_c',
        ),
        migrations.RemoveField(
            model_name='sondeo',
            name='id_ciudadano',
        ),
        migrations.RemoveField(
            model_name='sondeo',
            name='id_condicion',
        ),
        migrations.RemoveField(
            model_name='sondeo',
            name='id_pregunta',
        ),
        migrations.RemoveField(
            model_name='sondeo',
            name='img',
        ),
        migrations.RemoveField(
            model_name='sondeo',
            name='updated',
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'femenino')], max_length=15),
        ),
    ]
