# Generated by Django 4.1.1 on 2022-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0002_alter_ciudadano_con_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.CharField(max_length=250),
        ),
    ]
