# Generated by Django 4.1.1 on 2022-09-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0003_alter_pregunta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondeo',
            name='img',
            field=models.ImageField(blank=True, upload_to='sondeo/'),
        ),
    ]
