# Generated by Django 4.1.1 on 2022-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0004_alter_sondeo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='usuario',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
