# Generated by Django 4.1.1 on 2022-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0005_ciudadano_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondeo',
            name='id_ciudadano',
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='cuales',
            field=models.CharField(choices=[('N', 'Ninguno'), ('M', 'Movil'), ('C', ' Computador'), ('T', 'Tablet'), ('O', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='brr',
            field=models.CharField(blank=True, choices=[("{'barrio': 'Puente Aranda'}", "{'barrio': 'Puente Aranda'}"), ("{'barrio': 'Inmaculada concepcion'}", "{'barrio': 'Inmaculada concepcion'}"), ("{'barrio': 'Maria auxiliadora'}", "{'barrio': 'Maria auxiliadora'}")], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='grupo_p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
