# Generated by Django 4.1.1 on 2022-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0006_remove_sondeo_id_ciudadano_alter_ciudadano_cuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicion',
            name='rango_edad',
            field=models.CharField(blank=True, choices=[('Mayor que', 'Mayor que'), ('Menor que', 'Menor que')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='grupo_p',
            field=models.CharField(blank=True, choices=[("{'etnia': 'Raizal'}", "{'etnia': 'Raizal'}")], max_length=255, null=True),
        ),
    ]
