# Generated by Django 4.1.1 on 2022-09-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0007_condicion_rango_edad_alter_condicion_grupo_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('contestado', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroApp.ciudadano')),
                ('id_sondeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroApp.sondeo')),
            ],
        ),
    ]
