# Generated by Django 4.1.1 on 2022-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0008_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='reg',
            field=models.CharField(choices=[('Subsidiado', 'Subsidiado'), ('Contributivo', 'Contributivo')], max_length=30),
        ),
    ]
