# Generated by Django 4.1.1 on 2022-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0008_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicion',
            name='brr',
            field=models.CharField(blank=True, choices=[("{'barrio': 'kenedy'}", "{'barrio': 'kenedy'}")], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='condicion',
            name='grupo_p',
            field=models.CharField(blank=True, choices=[("{'etnia': 'raizal'}", "{'etnia': 'raizal'}")], max_length=255, null=True),
        ),
    ]
