# Generated by Django 4.1.1 on 2022-09-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0009_alter_ciudadano_reg'),
        ('registroApp', '0009_alter_condicion_brr_alter_condicion_grupo_p'),
    ]

    operations = [
    ]
